# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='status',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='service',
        ),
    ]
